import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { Check, CircleAlert, Network, ShieldCheck } from "lucide-react";
import "./styles.css";
import { AdapterRegistry, Architecture, ArrowRight, Checkpoint, CopyPanel, Footer, HeroLoop, Inspector, InteractiveLoop, Navbar, RunDemo, SectionHead, Trace } from "./components/Kage";
import { artifacts, cliText, configText, links, scope } from "./data/kage";

function Flow({ items, accentLast = false }: { items: string[]; accentLast?: boolean }) {
  return <div className="flow">{items.map((item, i) => <div className={accentLast && i === items.length - 1 ? "flow-item success" : "flow-item"} key={item + i}><span>{item}</span>{i < items.length - 1 && <ArrowRight />}</div>)}</div>;
}

function App() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a><Navbar />
    <main id="main">
      <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow">ENGINEERING WORKFLOW ORCHESTRATOR</p><h1>Engineering<br />is a <em>loop.</em></h1><p className="hero-lede">Plan. Execute. Test. Review. Fix. Kage does not implement a coding agent — it drives the ones you already have installed through that loop, and a verdict and an exit code decide when it stops.</p><div className="button-row"><a className="button" href="#run-demo">Explore Kage <ArrowRight /></a><a className="button secondary" href={links.github}>GitHub</a></div><p className="principle"><span>↳</span> Generation is not engineering. <strong>Iteration is.</strong></p></div><HeroLoop /></section>
      <div id="run-demo"><RunDemo /></div>

      <section className="editorial shell" id="overview"><p className="eyebrow">THE PREMISE</p><h2>Writing code is one step.<br /><span>Engineering is everything around it.</span></h2><div className="editorial-copy"><p>Software development requires understanding requirements, planning changes, implementing them, observing results, reviewing failures, and trying again.</p><p>Kage turns that process into an explicit agent loop.</p></div></section>

      <section className="section shell"><SectionHead eyebrow="THE KAGE LOOP" title="Keep iterating — until a verdict, an exit code, or the budget says stop." copy="Each stage transforms evidence into the context required by the next. Select a stage to inspect its contract." /><InteractiveLoop /></section>

      <section className="section shell comparison"><SectionHead eyebrow="WHY LOOPS MATTER" title="One-shot generation stops too early." /><div className="compare-grid"><article><span className="panel-label">CODE GENERATION</span><Flow items={["Prompt", "Code", "Done?"]} /><div className="result unknown">RESULT <strong>UNKNOWN</strong></div></article><article className="kage-compare"><span className="panel-label">KAGE / EVIDENCE-BACKED PROCESS</span><Flow items={["Task", "Plan", "Execute", "Test", "Review", "FAIL", "Fix", "Test", "Review", "PASS"]} accentLast /><div className="result verified">RESULT <strong>GATED</strong></div></article></div><p className="callout">Kage doesn’t treat generated code as proof that the task is complete.</p></section>

      <section className="section shell" id="architecture"><SectionHead eyebrow="MULTI-AGENT ARCHITECTURE" title="Three roles. No more." copy="Kage v0.1 is one planner, one executor, one reviewer. The engine names roles, never models: which harness fills a role is a line in .kage/config.yaml." /><div id="agents"><Architecture /></div></section>

      <section className="section shell"><SectionHead eyebrow="MODULAR INTELLIGENCE" title="Use the right intelligence for the right job." copy="Kage separates the engineering workflow from the underlying model, coding agent, or executor." /></section>
      <section className="section shell compact-top"><SectionHead eyebrow="BACKEND ADAPTER REGISTRY" title="Bring your own agents." copy="Driving already-installed coding agents is the premise, not a roadmap item. Each harness has an argv preset read from its own --help, and kage doctor reports which ones are on your PATH." /><AdapterRegistry /></section>

      <section className="section state-section"><div className="shell"><SectionHead eyebrow="ENGINEERING STATE" title="Every run has state." copy="A run is more than output. Plans, changes, validation, findings, and iterations remain connected." /><Inspector /></div></section>

      <section className="section shell"><SectionHead eyebrow="OBSERVABLE EXECUTION" title="Autonomous doesn’t mean invisible." copy="Every phase transition is written to state.json before the work begins, each agent's log is written line by line while the phase runs, and every prompt is kept verbatim. This is an illustrative trace of one run's real transitions." /><Trace /></section>

      <section className="section shell checkpoint-section"><SectionHead eyebrow="HUMAN IN THE LOOP" title="Where a run stops for a human." copy="Kage v0.1 has no interactive approval prompt — a run does not pause to ask. What it does instead: a BLOCKED verdict, or a review with no machine-readable verdict at all, stops the run for a human rather than guessing; agents work in an isolated worktree; and nothing is ever merged for you. The panel below sketches an approval gate that is not implemented." /><Checkpoint /></section>

      <section className="section failure-section"><div className="shell"><SectionHead eyebrow="FAILURE IS CONTEXT" title="Failure isn’t the end of a run." /><div className="failure-flow"><Flow items={["TEST FAILED", "TEST_RESULTS.md", "FIX", "TEST", "REVIEW", "PASS"]} accentLast /><div className="feedback-line">A BROKEN BUILD SPENDS THE REPAIR BUDGET · A REVIEW REJECTION SPENDS THE ITERATION BUDGET ↺</div></div><p className="big-statement">A broken build and a review finding are different failures, so they spend different budgets.</p></div></section>

      <section className="section shell objective-section"><SectionHead eyebrow="THE ACCEPTANCE GATE" title="Evidence, not an agent's word for it." copy="Explanatory example: adding middleware is not enough. Kage does not judge that itself — the validation commands you configured run in Kage's own process, and the reviewer judges the diff against the plan." /><div className="objective-card"><div className="objective-prompt"><span>EXAMPLE TASK</span><blockquote>“Add authentication to the API.”</blockquote><p>A one-shot agent may stop after creating middleware and report success. An exit code and a verdict are harder to talk around.</p></div><ul className="checklist">{["Does it compile?", "Do tests pass?", "Are protected routes protected?", "Are public routes accessible?", "Is configuration valid?", "Did existing behavior regress?"].map(x => <li key={x}><Check />{x}</li>)}</ul></div></section>

      <section className="section shell"><SectionHead eyebrow="ARTIFACTS, NOT CHAT HISTORY" title="Context moves through files on disk." copy="Three harnesses with three context windows cannot share a conversation. Every prompt is assembled from artifacts and stands alone — which is also why a run that crashes can be resumed, and read afterwards." /><div className="repo-map"><div className="repo-context">{artifacts.map((x, i) => <span key={x}><b>0{i + 1}</b>{x}</span>)}</div><div className="context-arrow"><ArrowRight /></div><div className="loop-core"><Network /><strong>.kage/runs/&lt;id&gt;/</strong><span>ONE DIRECTORY PER RUN</span></div></div></section>

      <section className="section shell"><SectionHead eyebrow="GIT SAFETY" title="By default, your working tree is not touched." copy="Agents work in a dedicated worktree under .kage/worktrees/, on a branch named kage/<run_id>. When the run finishes — completed, failed or blocked — Kage commits that worktree to the branch, so the work survives kage clean removing the checkout. Pass --no-isolate to run in the current tree instead. There is no GitHub or pull-request integration: nothing is merged for you." /><span className="status supported standalone-status">IMPLEMENTED · ISOLATE: TRUE BY DEFAULT · --no-isolate TO OPT OUT</span><Flow items={["Repository", "kage run", "Worktree", "Branch kage/<run_id>", "Test", "Review", "Commit", "git merge — yours to run"]} accentLast /></section>

      <section className="section parallel"><div className="shell"><span className="research-label">SCOPE · NOT IN v0.1</span><SectionHead eyebrow="WHAT KAGE DOES NOT DO" title="A line worth making reliable first." copy="These are decisions, not gaps. One run works one repository, because every guarantee Kage makes — isolation, the diff the reviewer judges, the commit that survives the run — is defined against a single worktree. Multi-repository and graph work belong to later versions." /><div className="repo-context">{scope.map((x, i) => <span key={x}><b>0{i + 1}</b>{x}</span>)}</div></div></section>

      <section className="section shell" id="docs"><SectionHead eyebrow="CONFIGURATION & CLI" title="Roles are bound to harnesses in one file." copy="Both panels are real. The config is .kage/config.yaml as src/config/schema.rs defines it — unknown keys are a hard error, so a sample that cannot be pasted is worse than none. Commands: kage init, kage doctor, kage run, kage status, kage resume, kage clean." /><div className="code-grid"><CopyPanel label=".kage/config.yaml" text={configText} /><CopyPanel label="CLI" text={cliText} /></div></section>

      <section className="section shell open-source" id="open-source"><div><p className="eyebrow">OPEN SOURCE</p><h2>Inspect the loop.</h2></div><div><p>Kage is MIT-licensed and written in Rust. Install it from a checkout with <code>cargo install --path .</code> — there is no published crate, and the name <code>kage</code> on crates.io belongs to an unrelated project.</p><p className="link-note"><CircleAlert /> Kage is v0.1. The README carries a Scope section and the development guide carries a Known gaps list; read both before depending on it.</p><div className="button-row"><a className="button" href={links.github}>github.com/algonacci/kage <ArrowRight /></a><a className="button secondary" href="#docs">Configuration and CLI</a></div></div></section>

      <section className="section manifold" id="manifold"><div className="shell"><SectionHead eyebrow="A MANIFOLD SYSTEMS PROJECT" title="Systems around intelligent agents." copy="Independent explorations of different relationships—not mandatory integrations." /><div className="ecosystem"><article><span>01</span><h3>Kamui</h3><strong>Agent ↔ Computer</strong><p>An exploration of an AI agent living in the terminal.</p></article><article><span>02</span><h3>Kumo</h3><strong>Human ↔ Agent</strong><p>An exploration of communication infrastructure for agents.</p></article><article className="active"><span>03</span><h3>Kage</h3><strong>Agent ↔ Engineering</strong><p>An engineering workflow orchestrator. Fully usable without the other two.</p></article></div></div></section>

      <section className="final-cta shell"><div className="completion-log"><span>ITERATION 01 <b>VERDICT: FAIL</b></span><span>ITERATION 02 <b>VERDICT: FAIL</b></span><span>ITERATION 03 <strong>VERDICT: PASS</strong></span><div><ShieldCheck /> RUN COMPLETED</div></div><div><p className="eyebrow">THE NEXT ITERATION</p><h2>Don’t stop at generated.</h2><p>A premium model plans, a cheap model implements, your test suite decides whether it works, and a third model reviews — up to a hard iteration cap, so a run can never spin forever.</p><div className="button-row"><a className="button" href={links.getKage}>Get Kage <ArrowRight /></a><a className="button secondary" href={links.github}>GitHub</a></div></div></section>
    </main><Footer />
  </>;
}

createRoot(document.getElementById("root") as HTMLElement).render(<StrictMode><App /></StrictMode>);
